runner_cfg:
  seed: 114514
  output_dir: results/buildings/
  optimizer_and_scheduler_cfg:
    param_dict_cfg:
      lr_prompt_learner_context: 0.0
      lr_prompt_learner_ranks: 1.0e-05
      lr_image_encoder: 1.0e-05
      lr_image_adapter: 1.0e-05
      lr_regressor: 1.0e-05
      lr_text_encoder: 0.0
      lr_logit_scale: 0.0
      staged_lr_image_encoder:
        new_layers: []
        base_lr_mult: 1.0
        new_lr_mult: 1.0
    optimizer_cfg:
      optimizer_name: radam
      lr: 0.0001
      weight_decay: 0.0
      momentum: 0.9
      sgd_dampening: 0.0
      sgd_nesterov: false
      rmsprop_alpha: 0.99
      adam_beta1: 0.9
      adam_beta2: 0.999
      staged_lr: null
      lookahead: false
    lr_scheduler_cfg:
      lr_scheduler_name: multi_step
      stepsize:
      - 60
      gamma: 0.1
      max_epochs: &max_epochs 50
      warmup_epoch: 0
      warmup_cons_lr: 1.0e-05
      warmup_min_lr: 1.0e-05
      warmup_type: constant
      warmup_recount: true
  load_weights_cfg:
    init_model_weights: null
    init_prompt_learner_weights: null
    init_image_encoder_weights: null
    init_image_adapter_weights: null
    init_text_encoder_weights: null
    init_location_encoder_weights: null
    init_regressor_weights: null
  loss_weights:
    ce_loss: 1.0
    kl_loss: 1.0
    reg_loss: 1.0
  model_cfg:
    type: RegCLIPSSR
    prompt_learner_cfg:
      type: PlainPromptLearner
      num_ranks: 7
      num_base_ranks: 3
      num_tokens_per_rank: 1
      num_context_tokens: 10
      rank_tokens_position: tail
      init_rank_path: data/classnames_buildings_class.txt
      init_context: 'built year estimation: the built year of the building is'
      rank_specific_context: false
      interpolation_type: linear
    text_encoder_name: ViT-B/16
    image_encoder_name: ViT-B/16
data_cfg:
  train_images_root: data/BUILDING
  val_images_root: data/BUILDING
  test_images_root: data/BUILDING
  train_data_file: data/BUILDING/data_list/train.txt
  val_data_file: data/BUILDING/data_list/valid.txt
  test_data_file: data/BUILDING/data_list/test.txt
  few_shot:
    num_shots: 0
  label_distributed_shift:
    num_topk_scaled_class: 0
    scale_factor: 1.0
  use_long_tail: false
  transforms_cfg:
    input_transforms:
    - random_resized_crop
    - random_hflip
    - normalize
    input_resize:
    - 256
    - 256
    input_size:
    - 224
    - 224
    pixel_mean:
    - 0.485
    - 0.456
    - 0.406
    pixel_std:
    - 0.229
    - 0.224
    - 0.225
  train_dataloder_cfg:
    num_workers: 8
    batch_size: 64
    shuffle: true
  eval_dataloder_cfg:
    num_workers: 8
    batch_size: 64
    shuffle: false
  test_location: true
trainer_cfg:
  max_epochs: *max_epochs
  precision: 16
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  fast_dev_run: false
test_only: true